#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jan 30 17:12:34 PST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim testbench_mcu_behav -key {Behavioral:sim_1:Functional:testbench_mcu} -tclbatch testbench_mcu.tcl -view /home/jared/Dev/otter/OtterV5/testbench_mcu_behav.wcfg -log simulate.log"
xsim testbench_mcu_behav -key {Behavioral:sim_1:Functional:testbench_mcu} -tclbatch testbench_mcu.tcl -view /home/jared/Dev/otter/OtterV5/testbench_mcu_behav.wcfg -log simulate.log

