#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jan 24 11:30:58 PST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto f476bf0707864d349c8de5a339b72e32 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot OTTER_Wrapper_Programmable_behav xil_defaultlib.OTTER_Wrapper_Programmable xil_defaultlib.glbl -log elaborate.log"
xelab -wto f476bf0707864d349c8de5a339b72e32 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot OTTER_Wrapper_Programmable_behav xil_defaultlib.OTTER_Wrapper_Programmable xil_defaultlib.glbl -log elaborate.log

