# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jared/Dev/otter/otter_project/otter_project.cache/wt [current_project]
set_property parent.project_path /home/jared/Dev/otter/otter_project/otter_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/jared/Dev/otter/otter_project/otter_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/jared/Dev/otter/otter_project/sources/otter_memory.mem
read_verilog -library xil_defaultlib -sv {
  /home/jared/Dev/otter/otter_project/sources/ArithLogicUnit.sv
  /home/jared/Dev/otter/otter_project/sources/BCD.sv
  /home/jared/Dev/otter/otter_project/sources/CU_Decoder.sv
  /home/jared/Dev/otter/otter_project/sources/CathodeDriver.sv
  /home/jared/Dev/otter/otter_project/sources/Mult4to1.sv
  /home/jared/Dev/otter/otter_project/sources/ProgCount.sv
  /home/jared/Dev/otter/otter_project/sources/SevSegDisp.sv
  /home/jared/Dev/otter/otter_project/sources/bram_dualport.sv
  /home/jared/Dev/otter/otter_project/sources/debounce_one_shot.sv
  /home/jared/Dev/otter/otter_project/sources/otter_mcu_pipeline_template.sv
  /home/jared/Dev/otter/otter_project/sources/registerFile.sv
  /home/jared/Dev/otter/otter_project/sources/OTTER_Wrapper.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jared/Dev/otter/otter_project/sources/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/jared/Dev/otter/otter_project/sources/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top OTTER_Wrapper_Programmable -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef OTTER_Wrapper_Programmable.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file OTTER_Wrapper_Programmable_utilization_synth.rpt -pb OTTER_Wrapper_Programmable_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
