webtalk_init -webtalk_dir /home/jared/Dev/otter/otter_project/otter_project.sim/sim_1/behav/xsim/xsim.dir/OTTER_Wrapper_Programmable_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 24 11:34:25 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "28861ce1-e6a7-451a-a47b-b63a3c734cd4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f476bf0707864d349c8de5a339b72e32" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2972.406 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "206143250 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.82_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125804_KB" -context "xsim\\usage"
webtalk_transmit -clientid 547515747 -regid "" -xml /home/jared/Dev/otter/otter_project/otter_project.sim/sim_1/behav/xsim/xsim.dir/OTTER_Wrapper_Programmable_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jared/Dev/otter/otter_project/otter_project.sim/sim_1/behav/xsim/xsim.dir/OTTER_Wrapper_Programmable_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jared/Dev/otter/otter_project/otter_project.sim/sim_1/behav/xsim/xsim.dir/OTTER_Wrapper_Programmable_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
